spring:
  config:
    activate: # ?? profile? ??? ??? ?? ??? ??? ?????
      on-profile: local
    import: optional:configserver:http://localhost:8088 # optional: ?? ??? ??? ? ?? ?????? ?? ???? ?? ?
  application:
    name: user # cloud config client? spring.application.name? cloud-config ???? ?? ??? ??? ??? ??
    # ?? spring.application.name? config-server? ?? ??? ???? ??? ????? ??.