spring:
  application:
    name: default, eureka-client, user  # user -> git 저장소, default -> vault 저장소에서 찾을 설정파일 이름
    # cloud config client의 spring.application.name은 cloud-config 에 어느 설정파일을 찾아갈지 알려주는 역할을 한다.
    # 최종 spring.application.name은 config-server의 값으로 오버라이딩된다.
  config:
    activate: # 특정 profile에서 활성화하도록 설정
      on-profile: local
    import: optional:configserver:http://localhost:8888 # optional: 옆의 서버에 접속을 못 해도 애플리케이션이 실행되도록 설정
